name       : openssh
version    : 9.4_p1
release    : 51
source     :
    - https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.4p1.tar.gz : 3608fd9088db2163ceb3e600c85ab79d0de3d221e59192ea1923e23263866a85
homepage   : https://www.openssh.com/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - ISC
    - MIT
summary    :
    - OpenSSH (OpenBSD Secure Shell)
    - server : OpenSSH Daemon
description: |
    OpenSSH is a free version of secure shell tools developed by the OpenBSD project to help facilitate secure connections and communications.
component  :
    - network.clients
    - server : network.clients
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libedit)
    - pkgconfig(libfido2)
    - pkgconfig(libldns)
    - pkgconfig(libsystemd)
    - pkgconfig(libxcrypt)
    - pkgconfig(krb5)
    - groff
    - xauth
rundeps    :
    - server :
        - openssh
        - xauth
patterns   :
    - server :
        - /usr/sbin
        - /usr/lib/systemd/system
        - /usr/lib/sysusers.d
        - /usr/lib/tmpfiles.d/openssh-server.conf
        - /usr/lib64/openssh/sftp*
        - /usr/share/defaults/etc/ssh/moduli
        - /usr/share/defaults/etc/ssh/sshd_config
        - /usr/share/defaults/etc/pam.d/sshd
        - /usr/share/man/*/moduli*
        - /usr/share/man/*/sshd*
        - /usr/share/man/*/sftp-*
setup      : |
    %apply_patches

    %reconfigure --sysconfdir=/etc/ssh \
                 --datadir=/usr/share/sshd \
                 --with-pid-dir=/run \
                 --with-xauth=/usr/bin/xauth \
                 --with-kerberos5=/usr \
                 --with-ldns=/usr \
                 --with-libedit \
                 --with-md5-passwords \
                 --with-pam \
                 --with-ssl-engine \
                 --with-systemd \
                 --with-security-key-builtin \
                 --with-privsep-path=/var/lib/sshd
build      : |
    %make
install    : |
    %make_install

    # PAM
    install -Dm 00644 $pkgfiles/sshd.pam $installdir/usr/share/defaults/etc/pam.d/sshd

    # systemd
    install -Dm 00644 $pkgfiles/sshd.service $installdir/usr/lib/systemd/system/sshd.service
    install -Dm 00644 $pkgfiles/sshd@.service $installdir/usr/lib/systemd/system/sshd@.service
    install -Dm 00644 $pkgfiles/sshd-keygen.service $installdir/usr/lib/systemd/system/sshd-keygen.service

    # Folks want ssh-copy-id :)
    install -Dm 00755 contrib/ssh-copy-id $installdir/usr/bin/.

    install -Dm 00644 $pkgfiles/openssh.tmpfiles $installdir/usr/lib/tmpfiles.d/openssh.conf
    install -Dm 00644 $pkgfiles/openssh-server.tmpfiles $installdir/usr/lib/tmpfiles.d/openssh-server.conf
    install -Dm 00644 $pkgfiles/openssh.sysusers $installdir/usr/lib/sysusers.d/openssh.conf

    # Stateless
    install -dm00755 $installdir/usr/share/defaults/etc/
    mv $installdir/etc/ssh $installdir/usr/share/defaults/etc/
    ls -ahl $installdir/var/lib
    rmdir $installdir/var/lib/sshd
    rmdir $installdir/var/lib
    rmdir $installdir/var
    rmdir $installdir/etc
