name       : openssh
version    : 7.6_p1
release    : 22
source     :
    - https://mirror.leaseweb.com/pub/OpenBSD/OpenSSH/portable/openssh-7.6p1.tar.gz : a323caeeddfe145baaa0db16e98d784b1fbc7dd436a6bf1f479dfd5cd1d21723
homepage   : http://www.openssh.org
license    :
    - BSD
summary    :
    - OpenSSH (OpenBSD Secure Shell)
    - server : OpenSSH Daemon
component  :
    - network.clients
    - server : network.clients
builddeps  :
    - xauth
rundeps    :
    - server :
        - openssh
        - xauth
patterns   :
    - server :
        - /usr/sbin
        - /usr/lib/systemd/system
        - /usr/lib/sysusers.d
        - /usr/lib/tmpfiles.d
        - /etc/ssh/sshd_config
        - /usr/lib64/openssh/sftp*
        - /usr/share/man/*/sshd*
        - /usr/share/man/*/sftp-*
description: |
    OpenSSH is a free version of secure shell tools developed by the OpenBSD project to help facilitate secure connections and communications.
setup      : |
    %configure --sysconfdir=/etc/ssh \
               --datadir=/usr/share/sshd \
               --with-xauth=/usr/bin/xauth \
               --with-md5-passwords \
               --with-pam \
               --with-privsep-path=/var/lib/sshd
build      : |
    %make
install    : |
    %make_install

    # Make PAM + systemd work
    install -D -m 00644 $pkgfiles/sshd.pam $installdir/etc/pam.d/sshd
    install -D -m 00644 $pkgfiles/sshd.service $installdir/usr/lib/systemd/system/sshd.service
    install -m 00644 $pkgfiles/sshd@.service $installdir/usr/lib/systemd/system/sshd@.service

    # Folks want ssh-copy-id :)
    install -m 00755 contrib/ssh-copy-id $installdir/usr/bin/.

    install -D -m 00644 $pkgfiles/openssh.tmpfiles $installdir/usr/lib/tmpfiles.d/openssh.conf
    install -D -m 00644 $pkgfiles/openssh.sysusers $installdir/usr/lib/sysusers.d/openssh.conf

    rm -rf $installdir/var
